name: Continuous Deployment

on: 
  push:
    branches:
      - develop

jobs:
  build-js:
    name: Build Js/Css
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Npm Build
        run: |
          npm install
          npm run prod
          cat public/mix-manifest.json
      - name: Upload build files
        uses: actions/upload-artifact@v1
        with:
          name: assets
          path: public
  
  deploy:
    name: Deploy to Staging
    runs-on: ubuntu-latest
    # Note tht this needs build-js to completed succesfully
    needs: [build-js]
    if: github.ref == 'refs/heads/develop'
    steps:
    - uses: actions/checkout@v1
    - name: Download build assets
      uses: actions/download-artifact@v1
      with:
        name: assets
        path: public
    - name: Setup PHP
      uses: shivammathur/setup-php@master
      with:
        php-version: 7.3
        extension-csv: mbstring, bcmath
    - name: Composer install
      run: composer install
    - name: Setup Deployer
      uses: atymic/deployer-php-action@master
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
        ssh-known-hosts: ${{ secrets.SSH_KNOWN_HOSTS }} 
    - name: Deploy to Prod
      run: |
        whoami
        pwd
        ls -al

