name: Continuous Deployment

on: 
  push:
    branches: 
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2-beta
        with:
          node-version: '16'
          check-latest: true

      - name: Install NPM dependencies
        run: npm install

      - name: Compile assets for production
        run: npm run production
      
      - name: Setup PHP
        uses: shivammathur/setup-php@master
        with:
          php-version: 8
          coverage: none
      
      - name: Copy .env
        run: php -r "file_exists('.env') || copy('.env.example', '.env');"

      - name: Install Dependencies
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
      
      - name: Generate key
        run: php artisan key:generate

  deploy:
    name: Deploy to Staging
    runs-on: ubuntu-latest
    needs: [build]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deployment
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_KNOWN_HOST }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          username: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /var/www/example.com/html
            git checkout -f 
            git pull